// <auto-generated />
using System;
using Dk.Odense.SSP.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dk.Odense.SSP.Infrastructure.Migrations
{
    [DbContext(typeof(SspDbContext))]
    [Migration("20190118120642_haha")]
    partial class haha
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Agenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgendaNumber");

                    b.Property<bool>("AgendaSent");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("MeetingHeld");

                    b.HasKey("Id");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.AgendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Agenda_Id");

                    b.Property<Guid?>("Categorization_Id");

                    b.Property<DateTime?>("ProcesseDate");

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.HasIndex("Agenda_Id");

                    b.HasIndex("Categorization_Id");

                    b.ToTable("AgendaItems");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.AreaRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Priority");

                    b.Property<string>("SearchValue");

                    b.Property<Guid>("SspArea_Id");

                    b.Property<string>("System");

                    b.HasKey("Id");

                    b.HasIndex("SspArea_Id");

                    b.ToTable("AreaRules");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DrugRelationship");

                    b.Property<string>("DrugRelationshipElaborate");

                    b.Property<int>("FutureDreams");

                    b.Property<string>("FutureDreamsElaborate");

                    b.Property<int>("GoodFriends");

                    b.Property<string>("GoodFriendsElaborate");

                    b.Property<int>("PositiveSupport");

                    b.Property<string>("PositiveSupportElaborate");

                    b.Property<int>("Skills");

                    b.Property<string>("SkillsElaborate");

                    b.Property<int>("SocialBehavior");

                    b.Property<string>("SocialBehaviorElaborate");

                    b.HasKey("Id");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Categorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DaysToExpire");

                    b.Property<bool>("DeleteAfterSspEnd");

                    b.Property<DateTime?>("ValidUntil");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Categorizations");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Concern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CrimeConcern");

                    b.Property<int>("NotifyConcern");

                    b.Property<int>("ReportedToPolice");

                    b.HasKey("Id");

                    b.ToTable("Concerns");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Grouping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Groupings");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.InternalSchoolData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateFirst");

                    b.Property<DateTime>("DateLast");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SchoolData");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("Person_Id");

                    b.Property<string>("Reporter");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("Person_Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Birthday");

                    b.Property<DateTime>("LastVerified");

                    b.Property<string>("Name");

                    b.Property<Guid?>("SchoolData_Id");

                    b.Property<string>("SocialSecNum");

                    b.Property<Guid?>("SspArea_Id");

                    b.Property<DateTime?>("SspStopDate");

                    b.HasKey("Id");

                    b.HasIndex("SchoolData_Id")
                        .IsUnique()
                        .HasFilter("[SchoolData_Id] IS NOT NULL");

                    b.HasIndex("SspArea_Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.PersonGrouping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Grouping_Id");

                    b.Property<Guid>("Person_Id");

                    b.HasKey("Id");

                    b.HasIndex("Grouping_Id");

                    b.HasIndex("Person_Id");

                    b.ToTable("PersonGroupings");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.PoliceWorryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ValidUntil");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("PoliceWorryCategories");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.PoliceWorryRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ValidUntil");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("PoliceWorryRoles");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.ReportedPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ReportedAdress");

                    b.Property<string>("ReportedCpr");

                    b.Property<string>("ReportedName");

                    b.HasKey("Id");

                    b.ToTable("ReportedPersons");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Reporter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("ImmediateLeader");

                    b.Property<string>("ImmediateLeaderEmail");

                    b.Property<string>("ImmediateLeaderPhone");

                    b.Property<string>("Name");

                    b.Property<string>("Phonenumber");

                    b.Property<string>("Workplace");

                    b.HasKey("Id");

                    b.ToTable("Reporters");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Robustness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Assessment_Id");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("EnrollmentPlace");

                    b.Property<int>("Increment")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Person_Id");

                    b.Property<string>("ReplyRecipientMail");

                    b.Property<string>("ReplyRecipientName");

                    b.Property<Guid>("ReportedPerson_Id");

                    b.Property<Guid>("Reporter_Id");

                    b.HasKey("Id");

                    b.HasIndex("Assessment_Id");

                    b.HasIndex("Person_Id");

                    b.HasIndex("ReportedPerson_Id");

                    b.HasIndex("Reporter_Id");

                    b.ToTable("Robustnesses");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ValidUntil");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.SspArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ValidUntil");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("SspAreas");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Worry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AgendaItem_Id");

                    b.Property<bool>("Approved");

                    b.Property<Guid?>("Assessment_Id");

                    b.Property<Guid?>("Concern_Id");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CrimeScene");

                    b.Property<DateTime?>("Groundless");

                    b.Property<int>("Increment")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("PendingAutoVerify")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<Guid?>("Person_Id");

                    b.Property<Guid?>("PoliceWorryCategory_Id");

                    b.Property<Guid?>("PoliceWorryRole_Id");

                    b.Property<DateTime?>("Processed");

                    b.Property<Guid?>("ReportedPerson_Id");

                    b.Property<Guid>("Reporter_Id");

                    b.Property<Guid?>("Source_Id");

                    b.HasKey("Id");

                    b.HasIndex("AgendaItem_Id");

                    b.HasIndex("Assessment_Id");

                    b.HasIndex("Concern_Id")
                        .IsUnique()
                        .HasFilter("[Concern_Id] IS NOT NULL");

                    b.HasIndex("Person_Id");

                    b.HasIndex("PoliceWorryCategory_Id");

                    b.HasIndex("PoliceWorryRole_Id");

                    b.HasIndex("ReportedPerson_Id");

                    b.HasIndex("Reporter_Id");

                    b.HasIndex("Source_Id");

                    b.ToTable("Worries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.AgendaItem", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.Agenda", "Agenda")
                        .WithMany("AgendaItems")
                        .HasForeignKey("Agenda_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Categorization", "Categorization")
                        .WithMany("AgendaItems")
                        .HasForeignKey("Categorization_Id");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.AreaRule", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.SspArea", "SspArea")
                        .WithMany()
                        .HasForeignKey("SspArea_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Note", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.Person", "Person")
                        .WithMany("Notes")
                        .HasForeignKey("Person_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Person", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.InternalSchoolData", "SchoolData")
                        .WithOne("Person")
                        .HasForeignKey("Dk.Odense.SSP.Domain.Model.Person", "SchoolData_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.SspArea", "SspArea")
                        .WithMany()
                        .HasForeignKey("SspArea_Id");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.PersonGrouping", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.Grouping", "Grouping")
                        .WithMany()
                        .HasForeignKey("Grouping_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Person", "Person")
                        .WithMany("PersonGroupings")
                        .HasForeignKey("Person_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Robustness", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.Assessment", "Assessment")
                        .WithMany()
                        .HasForeignKey("Assessment_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Person", "Person")
                        .WithMany("Robustnesses")
                        .HasForeignKey("Person_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.ReportedPerson", "ReportedPerson")
                        .WithMany()
                        .HasForeignKey("ReportedPerson_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Reporter", "Reporter")
                        .WithMany()
                        .HasForeignKey("Reporter_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Worry", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.AgendaItem", "AgendaItem")
                        .WithMany("Worries")
                        .HasForeignKey("AgendaItem_Id");

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Assessment", "Assessment")
                        .WithMany()
                        .HasForeignKey("Assessment_Id");

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Concern", "Concern")
                        .WithOne("Worry")
                        .HasForeignKey("Dk.Odense.SSP.Domain.Model.Worry", "Concern_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Person", "Person")
                        .WithMany("Worries")
                        .HasForeignKey("Person_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.PoliceWorryCategory", "PoliceWorryCategory")
                        .WithMany("Worries")
                        .HasForeignKey("PoliceWorryCategory_Id");

                    b.HasOne("Dk.Odense.SSP.Domain.Model.PoliceWorryRole", "PoliceWorryRole")
                        .WithMany("Worries")
                        .HasForeignKey("PoliceWorryRole_Id");

                    b.HasOne("Dk.Odense.SSP.Domain.Model.ReportedPerson", "ReportedPerson")
                        .WithMany("Worries")
                        .HasForeignKey("ReportedPerson_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Reporter", "Reporter")
                        .WithMany()
                        .HasForeignKey("Reporter_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Source", "Source")
                        .WithMany("Worry")
                        .HasForeignKey("Source_Id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
