// <auto-generated />
using System;
using Dk.Odense.SSP.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dk.Odense.SSP.Infrastructure.Migrations
{
    [DbContext(typeof(SspDbContext))]
    [Migration("20220510095519_AddGroupingType")]
    partial class AddGroupingType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Agenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgendaNumber")
                        .HasColumnType("int");

                    b.Property<bool>("AgendaSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MeetingHeld")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.AgendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Agenda_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Categorization_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ProcesseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Agenda_Id");

                    b.HasIndex("Categorization_Id");

                    b.ToTable("AgendaItems");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.AreaRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SearchValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SspArea_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("System")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SspArea_Id");

                    b.ToTable("AreaRules");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DrugRelationship")
                        .HasColumnType("int");

                    b.Property<string>("DrugRelationshipElaborate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FutureDreams")
                        .HasColumnType("int");

                    b.Property<string>("FutureDreamsElaborate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoodFriends")
                        .HasColumnType("int");

                    b.Property<string>("GoodFriendsElaborate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositiveSupport")
                        .HasColumnType("int");

                    b.Property<string>("PositiveSupportElaborate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Skills")
                        .HasColumnType("int");

                    b.Property<string>("SkillsElaborate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SocialBehavior")
                        .HasColumnType("int");

                    b.Property<string>("SocialBehaviorElaborate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Categorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DaysToExpire")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteAfterSspEnd")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorizations");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Concern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CrimeConcern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotifyConcern")
                        .HasColumnType("int");

                    b.Property<int>("ReportedToPolice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Concerns");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Grouping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groupings");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.InternalSchoolData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateFirst")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLast")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SchoolData");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Person_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reporter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Person_Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastVerified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SchoolData_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SocialSecNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SspArea_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SspStopDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolData_Id")
                        .IsUnique()
                        .HasFilter("[SchoolData_Id] IS NOT NULL");

                    b.HasIndex("SspArea_Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.PersonGrouping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Grouping_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Person_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Grouping_Id");

                    b.HasIndex("Person_Id");

                    b.ToTable("PersonGroupings");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.PoliceWorryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PoliceWorryCategories");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.PoliceWorryRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PoliceWorryRoles");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.ReportedPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportedAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedCpr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReportedPersons");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Reporter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateLeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateLeaderEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateLeaderPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workplace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reporters");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Robustness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Assessment_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnrollmentPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Increment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Person_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplyRecipientMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyRecipientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReportedPerson_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Reporter_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Assessment_Id");

                    b.HasIndex("Person_Id");

                    b.HasIndex("ReportedPerson_Id");

                    b.HasIndex("Reporter_Id");

                    b.ToTable("Robustnesses");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.SspArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SspAreas");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Worry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgendaItem_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Assessment_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Concern_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrimeScene")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Groundless")
                        .HasColumnType("datetime2");

                    b.Property<int>("Increment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("PendingAutoVerify")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("Person_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PoliceWorryCategory_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PoliceWorryRole_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Processed")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReportedPerson_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Reporter_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Source_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgendaItem_Id");

                    b.HasIndex("Assessment_Id");

                    b.HasIndex("Concern_Id")
                        .IsUnique()
                        .HasFilter("[Concern_Id] IS NOT NULL");

                    b.HasIndex("Person_Id");

                    b.HasIndex("PoliceWorryCategory_Id");

                    b.HasIndex("PoliceWorryRole_Id");

                    b.HasIndex("ReportedPerson_Id");

                    b.HasIndex("Reporter_Id");

                    b.HasIndex("Source_Id");

                    b.ToTable("Worries");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.AgendaItem", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.Agenda", "Agenda")
                        .WithMany("AgendaItems")
                        .HasForeignKey("Agenda_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Categorization", "Categorization")
                        .WithMany("AgendaItems")
                        .HasForeignKey("Categorization_Id");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.AreaRule", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.SspArea", "SspArea")
                        .WithMany()
                        .HasForeignKey("SspArea_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Note", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.Person", "Person")
                        .WithMany("Notes")
                        .HasForeignKey("Person_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Person", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.InternalSchoolData", "SchoolData")
                        .WithOne("Person")
                        .HasForeignKey("Dk.Odense.SSP.Domain.Model.Person", "SchoolData_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.SspArea", "SspArea")
                        .WithMany()
                        .HasForeignKey("SspArea_Id");
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.PersonGrouping", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.Grouping", "Grouping")
                        .WithMany("PersonGroupings")
                        .HasForeignKey("Grouping_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Person", "Person")
                        .WithMany("PersonGroupings")
                        .HasForeignKey("Person_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Robustness", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.Assessment", "Assessment")
                        .WithMany()
                        .HasForeignKey("Assessment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Person", "Person")
                        .WithMany("Robustnesses")
                        .HasForeignKey("Person_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dk.Odense.SSP.Domain.Model.ReportedPerson", "ReportedPerson")
                        .WithMany()
                        .HasForeignKey("ReportedPerson_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Reporter", "Reporter")
                        .WithMany()
                        .HasForeignKey("Reporter_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dk.Odense.SSP.Domain.Model.Worry", b =>
                {
                    b.HasOne("Dk.Odense.SSP.Domain.Model.AgendaItem", "AgendaItem")
                        .WithMany("Worries")
                        .HasForeignKey("AgendaItem_Id");

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Assessment", "Assessment")
                        .WithMany()
                        .HasForeignKey("Assessment_Id");

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Concern", "Concern")
                        .WithOne("Worry")
                        .HasForeignKey("Dk.Odense.SSP.Domain.Model.Worry", "Concern_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Person", "Person")
                        .WithMany("Worries")
                        .HasForeignKey("Person_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.PoliceWorryCategory", "PoliceWorryCategory")
                        .WithMany("Worries")
                        .HasForeignKey("PoliceWorryCategory_Id");

                    b.HasOne("Dk.Odense.SSP.Domain.Model.PoliceWorryRole", "PoliceWorryRole")
                        .WithMany("Worries")
                        .HasForeignKey("PoliceWorryRole_Id");

                    b.HasOne("Dk.Odense.SSP.Domain.Model.ReportedPerson", "ReportedPerson")
                        .WithMany("Worries")
                        .HasForeignKey("ReportedPerson_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Reporter", "Reporter")
                        .WithMany()
                        .HasForeignKey("Reporter_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dk.Odense.SSP.Domain.Model.Source", "Source")
                        .WithMany("Worry")
                        .HasForeignKey("Source_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
