//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasitWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://odknet.dk/webservices/", ConfigurationName="FasitWS.FasitWSSoap")]
    public interface FasitWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://odknet.dk/webservices/GetJournal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FasitWS.Journal[]> GetJournalAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string Cpr);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://odknet.dk/webservices/GetSager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FasitWS.Sager[]> GetSagerAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string Cpr);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://odknet.dk/webservices/GetSagsbehandlere", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FasitWS.Sagsbehandlere[]> GetSagsbehandlereAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string Cpr);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://odknet.dk/webservices/Nagios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> NagiosAsync(string SystemUserID, string SystemPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://odknet.dk/webservices/NagiosDB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> NagiosDBAsync(string SystemUserID, string SystemPassword);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://odknet.dk/webservices/")]
    public partial class Journal
    {
        
        private double idField;
        
        private string borger_CprField;
        
        private string journalTitelField;
        
        private string journalIndholdField;
        
        private System.DateTime dato_Haendelse_JournalnotatField;
        
        private string sagsIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Borger_Cpr
        {
            get
            {
                return this.borger_CprField;
            }
            set
            {
                this.borger_CprField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string JournalTitel
        {
            get
            {
                return this.journalTitelField;
            }
            set
            {
                this.journalTitelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string JournalIndhold
        {
            get
            {
                return this.journalIndholdField;
            }
            set
            {
                this.journalIndholdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Dato_Haendelse_Journalnotat
        {
            get
            {
                return this.dato_Haendelse_JournalnotatField;
            }
            set
            {
                this.dato_Haendelse_JournalnotatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SagsID
        {
            get
            {
                return this.sagsIDField;
            }
            set
            {
                this.sagsIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://odknet.dk/webservices/")]
    public partial class Sagsbehandlere
    {
        
        private int idField;
        
        private string sagsbehandlerBrugerIDField;
        
        private string sagsbehandlerIDField;
        
        private string sagsbehandlerNavnField;
        
        private string borger_CprField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SagsbehandlerBrugerID
        {
            get
            {
                return this.sagsbehandlerBrugerIDField;
            }
            set
            {
                this.sagsbehandlerBrugerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SagsbehandlerID
        {
            get
            {
                return this.sagsbehandlerIDField;
            }
            set
            {
                this.sagsbehandlerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SagsbehandlerNavn
        {
            get
            {
                return this.sagsbehandlerNavnField;
            }
            set
            {
                this.sagsbehandlerNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Borger_Cpr
        {
            get
            {
                return this.borger_CprField;
            }
            set
            {
                this.borger_CprField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://odknet.dk/webservices/")]
    public partial class Sager
    {
        
        private int idField;
        
        private string borger_CprField;
        
        private string hopIDField;
        
        private string sagsIDField;
        
        private string sagstitelField;
        
        private string sagstypeField;
        
        private long sagsstatusField;
        
        private string maalgruppeField;
        
        private string grupperingField;
        
        private string sagsbehandlerIDField;
        
        private string sagsbehandlerBrugerIDField;
        
        private string sagsbehandlerNavnField;
        
        private string sagsbehandlerEmailField;
        
        private string afdelingField;
        
        private string teamField;
        
        private System.DateTime datoStart_SagField;
        
        private System.DateTime datoSlut_SagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Borger_Cpr
        {
            get
            {
                return this.borger_CprField;
            }
            set
            {
                this.borger_CprField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string HopID
        {
            get
            {
                return this.hopIDField;
            }
            set
            {
                this.hopIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SagsID
        {
            get
            {
                return this.sagsIDField;
            }
            set
            {
                this.sagsIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sagstitel
        {
            get
            {
                return this.sagstitelField;
            }
            set
            {
                this.sagstitelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sagstype
        {
            get
            {
                return this.sagstypeField;
            }
            set
            {
                this.sagstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long Sagsstatus
        {
            get
            {
                return this.sagsstatusField;
            }
            set
            {
                this.sagsstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Maalgruppe
        {
            get
            {
                return this.maalgruppeField;
            }
            set
            {
                this.maalgruppeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Gruppering
        {
            get
            {
                return this.grupperingField;
            }
            set
            {
                this.grupperingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SagsbehandlerID
        {
            get
            {
                return this.sagsbehandlerIDField;
            }
            set
            {
                this.sagsbehandlerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SagsbehandlerBrugerID
        {
            get
            {
                return this.sagsbehandlerBrugerIDField;
            }
            set
            {
                this.sagsbehandlerBrugerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SagsbehandlerNavn
        {
            get
            {
                return this.sagsbehandlerNavnField;
            }
            set
            {
                this.sagsbehandlerNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SagsbehandlerEmail
        {
            get
            {
                return this.sagsbehandlerEmailField;
            }
            set
            {
                this.sagsbehandlerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Afdeling
        {
            get
            {
                return this.afdelingField;
            }
            set
            {
                this.afdelingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Team
        {
            get
            {
                return this.teamField;
            }
            set
            {
                this.teamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime DatoStart_Sag
        {
            get
            {
                return this.datoStart_SagField;
            }
            set
            {
                this.datoStart_SagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime DatoSlut_Sag
        {
            get
            {
                return this.datoSlut_SagField;
            }
            set
            {
                this.datoSlut_SagField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface FasitWSSoapChannel : FasitWS.FasitWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class FasitWSSoapClient : System.ServiceModel.ClientBase<FasitWS.FasitWSSoap>, FasitWS.FasitWSSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FasitWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(FasitWSSoapClient.GetBindingForEndpoint(endpointConfiguration), FasitWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FasitWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FasitWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FasitWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FasitWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FasitWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<FasitWS.Journal[]> GetJournalAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string Cpr)
        {
            return base.Channel.GetJournalAsync(SystemBrugerID, SystemPassword, BrugerID, Cpr);
        }
        
        public System.Threading.Tasks.Task<FasitWS.Sager[]> GetSagerAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string Cpr)
        {
            return base.Channel.GetSagerAsync(SystemBrugerID, SystemPassword, BrugerID, Cpr);
        }
        
        public System.Threading.Tasks.Task<FasitWS.Sagsbehandlere[]> GetSagsbehandlereAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string Cpr)
        {
            return base.Channel.GetSagsbehandlereAsync(SystemBrugerID, SystemPassword, BrugerID, Cpr);
        }
        
        public System.Threading.Tasks.Task<bool> NagiosAsync(string SystemUserID, string SystemPassword)
        {
            return base.Channel.NagiosAsync(SystemUserID, SystemPassword);
        }
        
        public System.Threading.Tasks.Task<bool> NagiosDBAsync(string SystemUserID, string SystemPassword)
        {
            return base.Channel.NagiosDBAsync(SystemUserID, SystemPassword);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public new virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FasitWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FasitWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FasitWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://wsnetudv.odknet.dk/FasitWS/Ver100/fasitWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.FasitWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://wsnetudv.odknet.dk/FasitWS/Ver100/fasitWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            FasitWSSoap,
            
            FasitWSSoap12,
        }
    }
}
