//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UvvejWs
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://odknet.dk/webservices/", ConfigurationName="Uvvej.serviceSoap")]
    public interface serviceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://odknet.dk/webservices/Nagios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> NagiosAsync(string SystemBrugerID, string SystemPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://odknet.dk/webservices/NagiosDB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> NagiosDBAsync(string SystemBrugerID, string SystemPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://odknet.dk/webservices/getForloeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UvvejWs.Forloeb[]> getForloebAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string cpr);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://odknet.dk/webservices/getVejleder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UvvejWs.Vejleder[]> getVejlederAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string cpr);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://odknet.dk/webservices/")]
    public partial class Forloeb
    {
        
        private string startDatoField;
        
        private string slutDatoField;
        
        private string registeretField;
        
        private string statusField;
        
        private string stedField;
        
        private string underplaceringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StartDato
        {
            get
            {
                return this.startDatoField;
            }
            set
            {
                this.startDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SlutDato
        {
            get
            {
                return this.slutDatoField;
            }
            set
            {
                this.slutDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Registreret
        {
            get
            {
                return this.registeretField;
            }
            set
            {
                this.registeretField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sted
        {
            get
            {
                return this.stedField;
            }
            set
            {
                this.stedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Underplacering
        {
            get
            {
                return this.underplaceringField;
            }
            set
            {
                this.underplaceringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://odknet.dk/webservices/")]
    public partial class Vejleder
    {
        
        private string vejledernavnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Vejledernavn
        {
            get
            {
                return this.vejledernavnField;
            }
            set
            {
                this.vejledernavnField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface serviceSoapChannel : UvvejWs.serviceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class serviceSoapClient : System.ServiceModel.ClientBase<UvvejWs.serviceSoap>, UvvejWs.serviceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public serviceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(serviceSoapClient.GetBindingForEndpoint(endpointConfiguration), serviceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(serviceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(serviceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> NagiosAsync(string SystemBrugerID, string SystemPassword)
        {
            return base.Channel.NagiosAsync(SystemBrugerID, SystemPassword);
        }
        
        public System.Threading.Tasks.Task<bool> NagiosDBAsync(string SystemBrugerID, string SystemPassword)
        {
            return base.Channel.NagiosDBAsync(SystemBrugerID, SystemPassword);
        }
        
        public System.Threading.Tasks.Task<UvvejWs.Forloeb[]> getForloebAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string cpr)
        {
            return base.Channel.getForloebAsync(SystemBrugerID, SystemPassword, BrugerID, cpr);
        }
        
        public System.Threading.Tasks.Task<UvvejWs.Vejleder[]> getVejlederAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string cpr)
        {
            return base.Channel.getVejlederAsync(SystemBrugerID, SystemPassword, BrugerID, cpr);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public new virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.serviceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.serviceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.serviceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://wsnetudv.odknet.dk/ws_uvforloeb/Ver100/service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.serviceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://wsnetudv.odknet.dk/ws_uvforloeb/Ver100/service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            serviceSoap,
            
            serviceSoap12,
        }
    }
}
