//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PladshistorikWs
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://odknet.dk/webservices/", ConfigurationName="ServiceReference1.pladshistorikWSSoap")]
    public interface pladshistorikWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://odknet.dk/webservices/GetPladshistorikDiff", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PladshistorikWs.tilbudshistorik[]> GetPladshistorikDiffAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string cpr, int datediff);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://odknet.dk/webservices/GetPladshistorikAktuel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PladshistorikWs.tilbudshistorik[]> GetPladshistorikAktuelAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string cpr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://odknet.dk/webservices/GetPladshistorikAlle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PladshistorikWs.tilbudshistorik[]> GetPladshistorikAlleAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string cpr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://odknet.dk/webservices/Nagios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> NagiosAsync(string SystemUserID, string SystemPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://odknet.dk/webservices/NagiosDB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> NagiosDBAsync(string SystemUserID, string SystemPassword);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://odknet.dk/webservices/")]
    public partial class tilbudshistorik
    {
        
        private string typeField;
        
        private string afdelingsNavnField;
        
        private string dateFirstField;
        
        private string dateLastField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AfdelingsNavn
        {
            get
            {
                return this.afdelingsNavnField;
            }
            set
            {
                this.afdelingsNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dateFirst
        {
            get
            {
                return this.dateFirstField;
            }
            set
            {
                this.dateFirstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dateLast
        {
            get
            {
                return this.dateLastField;
            }
            set
            {
                this.dateLastField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface pladshistorikWSSoapChannel : PladshistorikWs.pladshistorikWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class pladshistorikWSSoapClient : System.ServiceModel.ClientBase<PladshistorikWs.pladshistorikWSSoap>, PladshistorikWs.pladshistorikWSSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public pladshistorikWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(pladshistorikWSSoapClient.GetBindingForEndpoint(endpointConfiguration), pladshistorikWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public pladshistorikWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(pladshistorikWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public pladshistorikWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(pladshistorikWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public pladshistorikWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PladshistorikWs.tilbudshistorik[]> GetPladshistorikDiffAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string cpr, int datediff)
        {
            return base.Channel.GetPladshistorikDiffAsync(SystemBrugerID, SystemPassword, BrugerID, cpr, datediff);
        }
        
        public System.Threading.Tasks.Task<PladshistorikWs.tilbudshistorik[]> GetPladshistorikAktuelAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string cpr)
        {
            return base.Channel.GetPladshistorikAktuelAsync(SystemBrugerID, SystemPassword, BrugerID, cpr);
        }
        
        public System.Threading.Tasks.Task<PladshistorikWs.tilbudshistorik[]> GetPladshistorikAlleAsync(string SystemBrugerID, string SystemPassword, string BrugerID, string cpr)
        {
            return base.Channel.GetPladshistorikAlleAsync(SystemBrugerID, SystemPassword, BrugerID, cpr);
        }
        
        public System.Threading.Tasks.Task<bool> NagiosAsync(string SystemUserID, string SystemPassword)
        {
            return base.Channel.NagiosAsync(SystemUserID, SystemPassword);
        }
        
        public System.Threading.Tasks.Task<bool> NagiosDBAsync(string SystemUserID, string SystemPassword)
        {
            return base.Channel.NagiosDBAsync(SystemUserID, SystemPassword);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public new virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.pladshistorikWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.pladshistorikWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.pladshistorikWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://wsnetudv.odknet.dk/pladshistorikws/Ver100/pladshistorikws.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.pladshistorikWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://wsnetudv.odknet.dk/pladshistorikws/Ver100/pladshistorikws.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            pladshistorikWSSoap,
            
            pladshistorikWSSoap12,
        }
    }
}
